##### CREATING TOKEN EMBEDDINGs..

In [2]:
import torch

In [4]:
import importlib
import tiktoken

In [8]:
input_ids = torch.tensor([2, 3, 5, 1])

In [12]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

________________________________________________________________________________________________________________________________________________________
class torch.nn.Embedding(num_embeddings, embedding_dim, padding_idx=None, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, sparse=False, _weight=None, _freeze=False, device=None, dtype=None)

A simple lookup table that stores embeddings of a fixed dictionary and size.

This module is often used to store word embeddings and retrieve them using indices. The input to the module is a list of indices, and the output is the corresponding word embeddings.
________________________________________________________________________________________________________________________________________________________

In [15]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


_____________________________________________________________________________________________________________________________________________________
We can see that the weight matrix of the embedding layer contains small, random values.These values are optimized during LLM training as part of the LLM optimization itself.

Moreover, we can see that the weight matrix has six rows and three columns. There is one row for each of the six possible tockens in the vocab. And there is one column for each of the three embedding dimensions..
_____________________________________________________________________________________________________________________________________________________

In [18]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


_____________________________________________________________________________________________________________________________________________________
The embedding layer is essentially a look-up operation that retrieves rows from the embedding layer's weight matrix via a token ID..
_____________________________________________________________________________________________________________________________________________________

In [24]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


_____________________________________________________________________________________________________________________________________________________
Each row in the output matrix is obtained via a lookup operation from the embedding weight matrix..
_____________________________________________________________________________________________________________________________________________________